import { prisma } from "@/lib/prisma";
import { getCategory } from "@/lib/utils";
import Link from "next/link";
import { format } from "date-fns";

export default async function PaymentsPage() {
    const players = await prisma.player.findMany({
        where: { active: true },
        include: { payments: true }
    });

    const currentYear = new Date().getFullYear();
    const currentMonthIdx = new Date().getMonth(); // 0-based
    const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];

    // Logic to calculate debts
    const debts = players.map(player => {
        // Skip if Primera? "Jugadores de primera pueden no ser socios y tampoco pagan la actividad" -> Assuming free for now unless specified
        const category = getCategory(player);
        if (category === "Primera") return null;

        // Skip if Scholarship? "No pagan la actividad BASQUET".
        // Assuming 'Payment' in DB represents the full required payment. 
        // If they are becados, maybe they pay 'Social' but if we only track 1 payment record...
        // Let's assume Becados are fully exempt from the main "Activity" payment we track, OR we should assume they must pay.
        // User said: "Becados... no pagan la actividad BASQUET".
        // The Excel sheet has "Social, Actividad".
        // If I see a payment record, it's paid.
        // Use simple logic: If scholarship, maybe ignore debts? 
        // "tengo que poder marcar los pagos de los jugadores no becados para eso subo... planilla... y marques quienes tienen deuda"
        // THIS IMPLIES: Only NON-BECADOS have debts generated by this system.
        if (player.scholarship) return null;

        const owedMonths = [];
        // Check months up to current
        for (let i = 0; i <= currentMonthIdx; i++) {
            // If importing, maybe we verify full year?
            // Let's check from Jan to Current.
            const hasPayment = player.payments.some(p => p.year === currentYear && p.month === (i + 1));
            if (!hasPayment) {
                owedMonths.push(months[i]);
            }
        }

        if (owedMonths.length === 0) return null;

        return {
            player,
            category,
            owedMonths
        };
    }).filter(Boolean); // Remote nulls

    return (
        <div>
            <h2 style={{ marginBottom: '1.5rem' }}>Reporte de Deudas ({currentYear})</h2>

            <div style={{ marginBottom: '1rem', display: 'flex', gap: '1rem' }}>
                <Link href="/dashboard/import" className="btn btn-primary">Importar Pagos (Excel)</Link>
            </div>

            <div className="card">
                {debts.length === 0 ? (
                    <p className="text-muted">No se encontraron deudas para jugadores activos no becados.</p>
                ) : (
                    <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                        <thead>
                            <tr style={{ borderBottom: '1px solid var(--border)' }}>
                                <th style={{ padding: '1rem' }}>Jugador</th>
                                <th style={{ padding: '1rem' }}>Categoría</th>
                                <th style={{ padding: '1rem' }}>Meses Adeudados</th>
                                <th style={{ padding: '1rem' }}>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {debts.map((item: any) => (
                                <tr key={item.player.id} style={{ borderBottom: '1px solid var(--border)' }}>
                                    <td style={{ padding: '1rem' }}>
                                        <div>{item.player.name}</div>
                                        <div style={{ fontSize: '0.8rem', color: 'var(--secondary)' }}>{item.player.phone || 'Sin teléfono'}</div>
                                    </td>
                                    <td style={{ padding: '1rem' }}>{item.category} - Tira {item.player.tira}</td>
                                    <td style={{ padding: '1rem' }}>
                                        {item.owedMonths.map((m: string) => (
                                            <span key={m} style={{ display: 'inline-block', background: '#fee2e2', color: '#991b1b', padding: '0.1rem 0.4rem', borderRadius: '4px', fontSize: '0.75rem', marginRight: '0.25rem', marginBottom: '0.25rem' }}>
                                                {m}
                                            </span>
                                        ))}
                                    </td>
                                    <td style={{ padding: '1rem' }}>
                                        {item.player.phone && (
                                            <a
                                                href={`https://wa.me/${item.player.phone.replace(/[^0-9]/g, '')}?text=Hola ${item.player.name}, te recordamos que adeudas los meses de: ${item.owedMonths.join(', ')} en All Boys Basquet.`}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                style={{ color: '#16a34a', marginRight: '1rem', fontWeight: 500 }}
                                            >
                                                WhatsApp
                                            </a>
                                        )}
                                        {item.player.email && (
                                            <a
                                                href={`mailto:${item.player.email}?subject=Deuda Cuota All Boys&body=Hola ${item.player.name}, te recordamos que adeudas: ${item.owedMonths.join(', ')}.`}
                                                style={{ color: 'var(--accent)', fontWeight: 500 }}
                                            >
                                                Email
                                            </a>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    );
}
